environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  nodejs_version: 7
os: Visual Studio 2017 # Windows Server 2016
install:
  - ps: Install-Product node $env:nodejs_version
  - java -version
  - mvn --version
  - node --version
  - npm --version
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - npm install
test_script:
  - npm run build-static
  - npm test
  - cd uw-frame-java/
  - mvn clean install
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - C:\Users\appveyor\.m2\ -> pom.xml
